service: danfy-serverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  region: us-east-2

plugins:
  - serverless-plugin-typescript

functions:
  app:
    handler: dev.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
