service: danfy-serverless

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
